import {analyzeUsage,selectRows,csvText,dayKey,utcDay} from './model.js';
import {createChart} from './chart.js';
const $=id=>document.getElementById(id);
const state={config:null,data:null,tab:'usage',page:1,busy:false,jobId:null,demo:false,cached:false,poll:0};
const charts=[createChart('remain','remain'),createChart('usage','daily')];
let dormTimer, pendingNavigation=null;
const CACHE='szu-electricity-data-v1', PREFS='szu-electricity-prefs-v1';
const fmt=(n,digits=2)=>n==null?'—':Number(n).toLocaleString('zh-CN',{minimumFractionDigits:digits,maximumFractionDigits:digits});
const localDate=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
const dateToday=()=>localDate(new Date());
const safeRead=key=>{try{return JSON.parse(localStorage.getItem(key))}catch{return null}};
const safeWrite=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{return false}};
function status(text,type=''){ $('status').textContent=text;document.querySelector('.status-line').className='status-line '+type; }
function range(days){const now=new Date();$('end').value=localDate(now);now.setDate(now.getDate()-days+1);$('begin').value=localDate(now);document.querySelectorAll('[data-days]').forEach(b=>{const selected=+b.dataset.days===days;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected))});describeRange();}
function describeRange(){$('range-description').textContent=`${$('begin').value} — ${$('end').value}`;}
function buildings(selected){const c=state.config.campuses.find(c=>c.name===$('campus').value);$('building').replaceChildren(...c.buildings.map(name=>new Option(name,name)));if(c.buildings.includes(selected))$('building').value=selected;}
function inputs(){return {campus:$('campus').value,building:$('building').value,room:$('room').value.trim(),begin:$('begin').value,end:$('end').value};}
function showDorm(){const d=inputs();$('side-room').textContent=d.room?`${d.building} · ${d.room}`:'选择你的宿舍';$('side-campus').textContent=d.campus;}
function validDorm(d){return state.config?.campuses.some(c=>c.name===d.campus&&c.buildings.includes(d.building))&&/^[0-9A-Za-z\-]{1,16}$/.test(d.room||'');}
async function rememberDorm(){const {campus,building,room}=inputs(),dorm={campus,building,room};if(!validDorm(dorm))return;safeWrite(PREFS,dorm);state.preferenceTask=(state.preferenceTask||Promise.resolve()).catch(()=>{}).then(()=>api('/api/preferences',dorm)).then(()=>{state.preferenceError=false}).catch(()=>{state.preferenceError=true});await state.preferenceTask;}
function dormChanged(){showDorm();clearTimeout(dormTimer);dormTimer=setTimeout(rememberDorm,250);}
function markNav(target){document.querySelectorAll('.nav').forEach(b=>{const active=b.dataset.target===target&&(!b.dataset.recordTab||b.dataset.recordTab===state.tab);b.classList.toggle('active',active);if(active)b.setAttribute('aria-current','location');else b.removeAttribute('aria-current')});}
function navigate(target,tab){if(tab)setTab(tab);markNav(target);const section=$(target);if($('data-area').hidden){pendingNavigation={target,tab};return}section.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}
function trackNavigation(){if($('data-area').hidden)return;const ids=['overview-section','remain-section','usage-section','records-section'];let target=ids[0];for(const id of ids){if($(id).getBoundingClientRect().top<=125)target=id}markNav(target);}
function busy(value){state.busy=value;document.body.classList.toggle('busy',value);$('query').disabled=value;$('cancel').hidden=!value;$('demo').disabled=value;$('welcome-demo').disabled=value;document.querySelectorAll('#query-form input,#query-form select,[data-days]').forEach(el=>el.disabled=value);}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':state.config.token},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.message||'本地服务响应异常。');return data;}
async function query(event){event?.preventDefault();if(state.busy)return;const request=inputs();if(request.begin>request.end){status('开始日期不能晚于结束日期。','error');return}if(utcDay(request.end)-utcDay(request.begin)>1096){status('单次查询最多三年，请缩短日期范围。','error');return}clearTimeout(dormTimer);showDorm();busy(true);status('正在准备查询，将读取全部用电与购电记录…','loading');try{await rememberDorm();const job=await api('/api/query',request);state.jobId=job.id;poll();}catch(e){fail(e.message)}}
function fail(message){clearTimeout(state.poll);busy(false);status(message+(state.data?' 当前保留的是之前显示的数据。':''),'error');$('restore').hidden=!safeRead(CACHE);}
async function poll(){try{const job=await api('/api/job');if(!state.busy)return;if(job.id!==state.jobId){fail('查询任务已被另一个页面替换，请重新查询。');return;}if(job.state==='running'){status(job.message,'loading');state.poll=setTimeout(poll,700)}else if(job.state==='done'){busy(false);state.demo=false;state.cached=false;state.data=job.data;state.page=1;resetFilters();const saved=safeWrite(CACHE,job.data);$('clear-cache').hidden=!saved;$('restore').hidden=true;render();status(`查询完成 · 用电 ${job.data.usage.length} 条 / ${job.data.usagePages} 页，购电 ${job.data.purchases.length} 条 / ${job.data.purchasePages} 页 · 已核对完整性${saved?'':' · 浏览器未允许保存缓存'}${state.preferenceError?' · 本机宿舍保存失败，暂保存在当前浏览器':''}`)}else{fail(job.message||'查询已中断。')}}catch{fail('无法连接本地查询服务，请重新双击“启动SZU电查查”。')}}
function resetFilters(){$('search').value='';$('buy-filter').replaceChildren(new Option('全部购买形式',''));for(const type of [...new Set(state.data.purchases.map(r=>r.buyType))])$('buy-filter').add(new Option(type,type));}
function setTab(tab){state.tab=tab;state.page=1;document.querySelectorAll('.record-tabs [data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);if(b.getAttribute('role')==='tab')b.setAttribute('aria-selected',String(b.dataset.tab===tab))});$('buy-filter').hidden=tab!=='purchases';if(state.data)renderTable();}
function render(){const d=state.data, a=analyzeUsage(d.usage);$('welcome').hidden=true;$('data-area').hidden=false;$('room-title').textContent=`${d.building} ${d.room} 室`;$('data-date').textContent=`${state.demo?'演示数据 · ':state.cached?'本机缓存 · ':''}${d.begin} — ${d.end}`;$('connection').textContent=state.demo?'演示模式':state.cached?'缓存数据':'本地查询';
 $('remain').textContent=fmt(a.latest?.remain);$('remain-note').textContent=a.latest?`记录日期 ${dayKey(a.latest)} · 非实时余额`:'查询范围内没有用电记录';$('energy-fill').style.width=(a.latest?Math.min(100,Math.max(0,a.latest.remain/200*100)):0)+'%';$('average').textContent=fmt(a.average);$('average-note').textContent=a.days?`基于 ${a.days} 天有效读数间隔`:'至少需要两天有效读数';$('estimated').textContent=fmt(a.estimate,1);
 if(a.estimate!==null){const target=new Date(dayKey(a.latest)+'T12:00:00');target.setDate(target.getDate()+Math.floor(a.estimate));$('estimate-note').textContent=`按记录日估算，约至 ${localDate(target)}`}else{$('estimate-note').textContent='暂无足够数据进行估算'}
 $('spending').textContent=fmt(d.purchases.reduce((s,r)=>s+r.money,0));$('purchase-note').textContent=`${d.purchases.length} 笔购电 · 共 ${fmt(d.purchases.reduce((s,r)=>s+r.amount,0))} 度`;$('usage-count').textContent=d.usage.length;$('purchase-count').textContent=d.purchases.length;
 const notes=[];if(state.demo)notes.push('当前为演示数据，用于体验界面，不代表你的宿舍电量。');if(state.cached)notes.push(`正在显示本机缓存，保存于 ${d.fetchedAt}。请重新查询以获取最新记录。`);if(a.latest&&a.latest.remain<20)notes.push('记录日剩余电量不足 20 度，建议及时确认最新余额。');if(a.latest&&utcDay(dateToday())-utcDay(a.latest.date)>2)notes.push(`最新用电记录为 ${dayKey(a.latest)}，请注意数据时效。`);if(a.gaps)notes.push(`${a.gaps} 段读数存在跨日间隔，图表按间隔日均展示。`);if(a.resets)notes.push(`${a.resets} 段累计读数回退，已从用电统计中排除。`);$('notice').hidden=!notes.length;$('notice').textContent=notes.join(' ');
 renderChart();renderTable();if(pendingNavigation){const {target,tab}=pendingNavigation;pendingNavigation=null;requestAnimationFrame(()=>navigate(target,tab))}}
function renderChart(){for(const chart of charts)chart.draw(state.data,$('tariff').value)}
function filtered(){return selectRows(state.data,state.tab,$('search').value,$('buy-filter').value,$('sort').value)}
function rowValues(r,intervals){if(state.tab==='purchases')return [r.date,r.room,r.amount,r.money,r.buyType,r.buyer];const interval=intervals.get(dayKey(r));const lastForDay=interval?.no===r.no;return [r.date,r.room,r.remain,lastForDay?interval?.delta:null,lastForDay?interval?.span:null,r.used,r.bought];}
function renderTable(){const rows=filtered(),usage=state.tab==='usage';const headers=usage?['记录时间','房间','剩余电量 / 度','间隔用电 / 度','累计用电 / 度','累计购电 / 度']:['购买时间','房间','购买电量 / 度','金额 / 元','购买形式','购买者'];const head=document.createElement('tr');for(const title of headers){const th=document.createElement('th');th.textContent=title;head.append(th)}$('table-head').replaceChildren(head);const pages=Math.max(1,Math.ceil(rows.length/12));state.page=Math.min(state.page,pages);$('table-body').replaceChildren();const intervals=new Map(analyzeUsage(state.data.usage).intervals.map(r=>[dayKey(r),r]));
 for(const r of rows.slice((state.page-1)*12,state.page*12)){const tr=document.createElement('tr');const values=rowValues(r,intervals);const cells=usage?[values[0],values[1],fmt(values[2]),fmt(values[3]),fmt(values[5]),fmt(values[6])]:[values[0],values[1],fmt(values[2]),fmt(values[3]),values[4],values[5]];cells.forEach((value,i)=>{const td=document.createElement('td');td.textContent=value;td.className='number';if(i===0){td.textContent=r.date.slice(0,10);const sub=document.createElement('span');sub.className='sub';sub.textContent=r.date.slice(11);td.append(sub)}if(usage&&i===3){const interval=intervals.get(dayKey(r));const sub=document.createElement('span');sub.className='sub';sub.textContent=interval?.no!==r.no?'同日非末次读数':interval.reset?'累计读数回退':interval.span>1?`${interval.span} 天间隔 · 日均 ${fmt(interval.daily)} 度`:interval.span===1?'1 天间隔':'无前序读数';td.append(sub)}tr.append(td)});$('table-body').append(tr)}
 if(!rows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=6;td.className='empty';td.textContent=$('search').value||$('buy-filter').value?'没有匹配的记录，试试调整筛选条件。':'该日期范围内没有记录。';tr.append(td);$('table-body').append(tr)}
 $('page-info').textContent=`${state.page} / ${pages}`;$('prev').disabled=state.page===1;$('next').disabled=state.page===pages;$('export').disabled=!rows.length;$('table-summary').textContent=usage?`筛选后 ${rows.length} 条 · 已读取查询范围内全部 ${state.data.usage.length} 条`:`筛选后 ${rows.length} 笔 · ${fmt(rows.reduce((s,r)=>s+r.amount,0))} 度 / ¥${fmt(rows.reduce((s,r)=>s+r.money,0))}`;}
function demo(){if(state.busy)return;const usage=[],purchases=[],now=new Date();let used=8200,bought=8400;for(let i=59;i>=0;i--){const date=new Date(now);date.setDate(date.getDate()-i);const key=localDate(date),delta=4.3+Math.sin(i*.51)*1.5+(i%7===0?2:0);used+=delta;if(i===40||i===15){bought+=142.86;purchases.push({no:purchases.length+1,room:'101',date:key+' 12:35:20',amount:142.86,money:100,buyType:'微信购电',buyer:'演示用户'})}usage.push({no:usage.length+1,room:'101',date:key+' 23:59:00',remain:Math.round((bought-used)*100)/100,used:Math.round(used*100)/100,bought})}state.data={campus:'新斋区',building:'紫薇斋',room:'101',begin:dayKey(usage[0]),end:dateToday(),fetchedAt:'演示',usage,purchases,complete:true};state.demo=true;state.cached=false;state.page=1;resetFilters();render();status('演示模式 · 数据为模拟生成，不会覆盖你的真实查询缓存。');$('restore').hidden=!safeRead(CACHE);}
function restore(){const data=safeRead(CACHE);if(!data||!Array.isArray(data.usage)||!Array.isArray(data.purchases)){status('没有可用缓存。','error');return}state.data=data;state.demo=false;state.cached=true;state.page=1;resetFilters();render();status(`已恢复上次查询 · ${data.fetchedAt} · 可重新查询更新数据。`);$('restore').hidden=true;$('clear-cache').hidden=false;}
async function startupQuery(){const job=await api('/api/job');if(job.state==='running'){
 const wanted=inputs();if(['campus','building','room','begin','end'].every(key=>job.request?.[key]===wanted[key])){busy(true);state.jobId=job.id;poll();return}
 busy(true);status('正在等待当前查询结束，随后自动查询我的宿舍近 30 天数据…','loading');state.poll=setTimeout(async()=>{if(!state.busy)return;busy(false);try{await startupQuery()}catch{fail('无法连接本地查询服务，请重新打开程序。')}},700);
 }else await query();}
async function init(){
 range(30);const savedTariff=safeRead('szu-electricity-tariff-v1');if(savedTariff!==null)$('tariff').value=savedTariff;
 $('today').textContent=new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'});$('end').max=dateToday();$('begin').max=dateToday();
 try{
  state.config=await api('/api/config');$('campus').replaceChildren(...state.config.campuses.map(c=>new Option(c.name,c.name)));
  const stored=state.config.preferences||safeRead(PREFS);const prefs=validDorm(stored||{})?stored:{campus:'新斋区',building:'紫薇斋',room:''};
  $('campus').value=prefs.campus;buildings(prefs.building);$('room').value=prefs.room;showDorm();
  const cached=safeRead(CACHE);if(cached&&cached.campus===prefs.campus&&cached.building===prefs.building&&cached.room===prefs.room&&Array.isArray(cached.usage)&&Array.isArray(cached.purchases)){state.data=cached;state.cached=true;resetFilters();render()}
  $('restore').hidden=!cached;$('clear-cache').hidden=!cached;
  if(validDorm(prefs))await startupQuery();else status('首次使用，请选择自己的宿舍并填写房间号；也可以先体验演示。');
 }catch{status('本地服务未连接，请重新双击“SZU电查查.exe”打开页面。','error');$('query').disabled=true;}
}
$('advanced-toggle').onclick=()=>{const expanded=$('advanced-toggle').getAttribute('aria-expanded')!=='true';$('advanced-toggle').setAttribute('aria-expanded',String(expanded));$('advanced-filters').hidden=!expanded};
$('tariff').addEventListener('input',()=>{if(!$('tariff').checkValidity())return;safeWrite('szu-electricity-tariff-v1',$('tariff').value);if(state.data)renderChart()});
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>navigate(b.dataset.target,b.dataset.recordTab));
window.addEventListener('scroll',()=>requestAnimationFrame(trackNavigation),{passive:true});
$('query-form').addEventListener('submit',query);$('campus').addEventListener('change',()=>{buildings();dormChanged()});$('building').addEventListener('change',dormChanged);$('room').addEventListener('input',dormChanged);document.querySelectorAll('[data-days]').forEach(b=>b.onclick=()=>range(+b.dataset.days));document.querySelectorAll('#begin,#end').forEach(el=>el.addEventListener('change',()=>{document.querySelectorAll('[data-days]').forEach(b=>{b.classList.remove('selected');b.setAttribute('aria-pressed','false')});describeRange()}));document.querySelectorAll('.record-tabs [data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));['search','buy-filter','sort'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',()=>{state.page=1;if(state.data)renderTable()}));$('prev').onclick=()=>{state.page--;renderTable()};$('next').onclick=()=>{state.page++;renderTable()};$('demo').onclick=demo;$('welcome-demo').onclick=demo;$('restore').onclick=restore;
$('clear-cache').onclick=()=>{try{localStorage.removeItem(CACHE)}catch{}$('clear-cache').hidden=true;$('restore').hidden=true;status('已清除本机记录缓存。当前页面的数据仍可查看，刷新后不会恢复。')};
$('cancel').onclick=async()=>{clearTimeout(state.poll);try{await api('/api/cancel',{});busy(false);status('已取消查询，之前的数据保持不变。')}catch{fail('取消失败，请重新打开查询服务。')}};
async function stopService(){try{await api('/api/stop',{});clearTimeout(state.poll);busy(false);$('query').disabled=true;document.body.classList.add('stopped');status('查询服务已关闭。下次使用时重新双击“启动SZU电查查”即可。');$('stop').disabled=true;$('stop-mobile').disabled=true}catch{status('查询服务已离线。')}}
$('stop').onclick=stopService;$('stop-mobile').onclick=stopService;
$('export').onclick=()=>{const intervals=new Map(analyzeUsage(state.data.usage).intervals.map(r=>[dayKey(r),r]));const headers=state.tab==='usage'?['记录时间','房间','剩余电量(度)','间隔用电(度)','间隔天数','累计用电(度)','累计购电(度)']:['购买时间','房间','购买电量(度)','购买金额(元)','购买形式','购买者'];const content=csvText(headers,filtered().map(r=>rowValues(r,intervals)));const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`${state.demo?'演示_':''}${state.data.building}_${state.data.room}_${state.tab==='usage'?'用电':'购电'}_${state.data.begin}_${state.data.end}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{if(state.data)renderChart()},100)});
init();
